### ISSUE TITLE
API updates

### ISSUE THREAD

**Issue by florian987** [pkyu/coastle#2]
I came accross your game and it's very fun!

I am the founder of Captain Coaster, and this is exactly the type of projects I was hoping to see when I published the API.

I saw on reddit you are missing some data and also some feedbacks regarding data quality. Feel free to ask me to add data you need on the API (basically everything on the website can be added) and also to report me main data quality issues so I can fix them. Happy to help :)

Also could you use github secret feature to store API key, as this is not supposed to be public

**Comment by pkyu** [comment]
Thank you so much for publishing your API and providing access to it! Making this project was so much fun and only possible because of your work. Seriously, I can’t thank you enough, and I’m glad I could create a project you think is fun using it.

I will work on making the API key secret as soon as I get home (sorry this wasn’t originally the case, I am a student and this was my first time utilizing APIs). I can also provide a list of data issues I’ve found in a bit. Normally I check the data for the next day’s coaster before the day changes so it hasn’t been too big of an issue though.

I think the biggest thing that would help if you added it to the API would be opening date for rides if possible. The game functions fine without it but I think it would definitely help a lot of people if they could narrow down year.

Thank you again for providing the API and contacting me in general. I’ve used your site a lot and it’s awesome to hear from the creator and know he’s happy to help with things :)

**Comment by florian987** [comment]
Just added opening date to the API, along with other missing data!

**Comment by ausisson** [comment]
this shit crazy

**Comment by pkyu** [comment]
> Just added opening date to the API, along with other missing data!

Thank you! I will work on making it so guesses will now show opening date soon.

I'm sorry, but I failed trying to make the API key secret as you asked. After looking into it for a while I'm pretty sure it is not possible with the way Coastle is made and won't be possible as long as I am using GitHub Pages to host the code. Because GitHub Pages hosts static sites (Coastle is a browser environment site) and this is a front-end only project, I cannot use environment variables which means I also cannot use the GitHub secret feature or hide the API key in any way. There is no backend so no matter what I do someone could find the API key.

I thought for a while and figured the best thing I could do for a static site would be to make it so people can't just read the code and have the key sitting their in plaintext  Basically, what I did is just store the API key in encoded format then have a method to decode it. If someone runs the code on their own they can still tell what the API key is. However, I figured that if anyone wants to access your API, rather than going through the effort to get my API key, they would just make a free account on your site and get their own. I also got the impression that it would be ok to have the API key public since CaptainCoaster's API is a read-only API (which I think is why you make it so anybody with an account on your site can get a key). 

Would this be good enough? I think to further hide it I'd have to restructure my code to not be browser environment then find a new hosting site. I want to make sure you're okay with it like this though, so if you aren't I'll respect your wishes and take down the site until I can do that in the future.

Thanks again for the help, and sorry again

**Comment by florian987** [comment]
Seems OK to me, as you said it's read-only and public data. We are using api keys to monitor usage and rate-limit requests, so if everyone on Github starts using yours, it's going to be a problem and I might have to reset it. For the time being it's perfectly fine for me ;)

Did you take a look at opening date on the API?

Also feel free to reach out for data quality problems if needed!

**Comment by pkyu** [comment]
Sounds good! And yes, I've been trying out different ways of adding opening date into the game without making the board look too cluttered. Also looking into maybe using the other information you added for creating more varied hints. Thank you!

I'll send a list of data quality problems in a bit. Currently in my final weeks of classes so probably after that.

I got finals right now but I'll compile a list of some data quality issues and send them next week. It'll probably be pretty short.
